//! NixOS configuration.nix generation
//!
//! Generates a valid NixOS configuration file from the installation configuration.

use crate::config::{BootLoader, InstallConfig};
use crate::error::{ConfigError, InstallerError};
use std::path::Path;

/// Generate a configuration.nix file from the installation configuration
pub fn generate_configuration(config: &InstallConfig) -> Result<String, InstallerError> {
    // Validate configuration first
    config
        .validate()
        .map_err(|e| InstallerError::Config(ConfigError::ValidationFailed(e)))?;

    let mut nix_config = String::new();

    // Header comment
    nix_config.push_str("# NixOS Configuration File\n");
    nix_config.push_str("# Generated by ekaos-install\n");
    nix_config.push_str("#\n");
    nix_config.push_str("# This configuration file contains the system settings you chose\n");
    nix_config
        .push_str("# during installation. You can edit this file to customize your system.\n");
    nix_config.push_str("#\n");
    nix_config.push_str("# For more information, see: https://nixos.org/manual/nixos/stable/\n\n");

    // Main configuration structure
    nix_config.push_str("{ config, pkgs, ... }:\n\n");
    nix_config.push_str("{\n");

    // Import hardware configuration
    nix_config.push_str("  # Include the results of the hardware scan\n");
    nix_config.push_str("  imports = [\n");
    nix_config.push_str("    ./hardware-configuration.nix\n");
    nix_config.push_str("  ];\n\n");

    // Boot loader configuration
    nix_config.push_str("  # Boot loader configuration\n");
    match config.bootloader {
        BootLoader::SystemdBoot => {
            nix_config.push_str("  boot.loader.systemd-boot.enable = true;\n");
            nix_config.push_str("  boot.loader.efi.canTouchEfiVariables = true;\n");
        }
        BootLoader::Grub => {
            nix_config.push_str("  boot.loader.grub.enable = true;\n");
            nix_config.push_str(
                "  boot.loader.grub.device = \"/dev/sda\"; # Update this to match your disk\n",
            );
            nix_config.push_str("  # boot.loader.grub.efiSupport = true; # Uncomment for UEFI\n");
            nix_config.push_str(
                "  # boot.loader.efi.canTouchEfiVariables = true; # Uncomment for UEFI\n",
            );
        }
    }
    nix_config.push_str("\n");

    // Networking configuration
    nix_config.push_str("  # Networking configuration\n");
    nix_config.push_str(&format!(
        "  networking.hostName = \"{}\";\n",
        config.hostname
    ));

    if config.network_manager {
        nix_config.push_str("  networking.networkmanager.enable = true;\n");
    } else {
        nix_config.push_str(
            "  # networking.networkmanager.enable = true; # Uncomment to enable NetworkManager\n",
        );
    }
    nix_config.push_str("\n");

    // Locale and timezone
    nix_config.push_str("  # Set your time zone\n");
    nix_config.push_str(&format!("  time.timeZone = \"{}\";\n\n", config.timezone));

    nix_config.push_str("  # Select internationalization properties\n");
    nix_config.push_str(&format!("  i18n.defaultLocale = \"{}\";\n", config.locale));
    nix_config.push_str("\n");

    // Console configuration
    nix_config.push_str("  # Console keymap\n");
    nix_config.push_str(&format!("  console.keyMap = \"{}\";\n\n", config.keymap));

    // User configuration
    nix_config.push_str("  # Define your user account\n");
    nix_config.push_str(&format!("  users.users.{} = {{\n", config.user.username));
    nix_config.push_str("    isNormalUser = true;\n");

    if let Some(full_name) = &config.user.full_name {
        if !full_name.is_empty() {
            nix_config.push_str(&format!("    description = \"{}\";\n", full_name));
        }
    }

    if config.user.is_admin {
        nix_config.push_str("    extraGroups = [ \"wheel\" \"networkmanager\" ];\n");
    } else {
        nix_config.push_str("    extraGroups = [ \"networkmanager\" ];\n");
    }

    nix_config.push_str("  };\n\n");

    // System packages
    nix_config.push_str("  # System packages\n");
    nix_config.push_str("  environment.systemPackages = with pkgs; [\n");
    nix_config.push_str("    vim\n");
    nix_config.push_str("    wget\n");
    nix_config.push_str("    git\n");
    nix_config.push_str("    htop\n");
    nix_config.push_str("  ];\n\n");

    // Services
    nix_config.push_str("  # Enable the OpenSSH daemon (optional)\n");
    nix_config.push_str("  # services.openssh.enable = true;\n\n");

    // System state version
    nix_config.push_str("  # This value determines the NixOS release from which the default\n");
    nix_config
        .push_str("  # settings for stateful data, like file locations and database versions\n");
    nix_config
        .push_str("  # on your system were taken. It's perfectly fine and recommended to leave\n");
    nix_config
        .push_str("  # this value at the release version of the first install of this system.\n");
    nix_config.push_str("  # Before changing this value read the documentation for this option\n");
    nix_config
        .push_str("  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).\n");
    nix_config.push_str("  system.stateVersion = \"24.05\"; # Did you read the comment?\n");
    nix_config.push_str("}\n");

    Ok(nix_config)
}

/// Write configuration to a file
pub fn write_configuration<P: AsRef<Path>>(
    config: &InstallConfig,
    path: P,
) -> Result<(), InstallerError> {
    let content = generate_configuration(config)?;
    std::fs::write(path.as_ref(), content).map_err(|e| {
        InstallerError::Config(ConfigError::WriteFailed {
            path: path.as_ref().display().to_string(),
            reason: e.to_string(),
        })
    })?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::UserConfig;

    fn create_test_config() -> InstallConfig {
        InstallConfig {
            hostname: "test-nixos".to_string(),
            user: UserConfig {
                username: "testuser".to_string(),
                full_name: Some("Test User".to_string()),
                is_admin: true,
                password: "testpass123".to_string(),
            },
            timezone: "America/New_York".to_string(),
            locale: "en_US.UTF-8".to_string(),
            keymap: "us".to_string(),
            bootloader: BootLoader::SystemdBoot,
            network_manager: true,
        }
    }

    #[test]
    fn test_generate_configuration_systemd_boot() {
        let config = create_test_config();
        let result = generate_configuration(&config);

        assert!(result.is_ok());
        let nix_config = result.unwrap();

        // Check key components are present
        assert!(nix_config.contains("{ config, pkgs, ... }:"));
        assert!(nix_config.contains("./hardware-configuration.nix"));
        assert!(nix_config.contains("boot.loader.systemd-boot.enable = true"));
        assert!(nix_config.contains("networking.hostName = \"test-nixos\""));
        assert!(nix_config.contains("time.timeZone = \"America/New_York\""));
        assert!(nix_config.contains("users.users.testuser"));
        assert!(nix_config.contains("description = \"Test User\""));
        assert!(nix_config.contains("extraGroups = [ \"wheel\" \"networkmanager\" ]"));
    }

    #[test]
    fn test_generate_configuration_grub() {
        let mut config = create_test_config();
        config.bootloader = BootLoader::Grub;

        let result = generate_configuration(&config);
        assert!(result.is_ok());

        let nix_config = result.unwrap();
        assert!(nix_config.contains("boot.loader.grub.enable = true"));
        assert!(nix_config.contains("boot.loader.grub.device"));
        assert!(!nix_config.contains("boot.loader.systemd-boot"));
    }

    #[test]
    fn test_generate_configuration_no_full_name() {
        let mut config = create_test_config();
        config.user.full_name = None;

        let result = generate_configuration(&config);
        assert!(result.is_ok());

        let nix_config = result.unwrap();
        assert!(!nix_config.contains("description ="));
    }

    #[test]
    fn test_generate_configuration_non_admin_user() {
        let mut config = create_test_config();
        config.user.is_admin = false;

        let result = generate_configuration(&config);
        assert!(result.is_ok());

        let nix_config = result.unwrap();
        assert!(nix_config.contains("extraGroups = [ \"networkmanager\" ]"));
        assert!(!nix_config.contains("\"wheel\""));
    }

    #[test]
    fn test_generate_configuration_invalid() {
        let mut config = create_test_config();
        config.user.username = "".to_string(); // Invalid username

        let result = generate_configuration(&config);
        assert!(result.is_err());
    }

    #[test]
    fn test_configuration_valid_nix_structure() {
        let config = create_test_config();
        let result = generate_configuration(&config);

        assert!(result.is_ok());
        let nix_config = result.unwrap();

        // Basic structural checks
        assert!(nix_config.contains("{\n"));
        assert!(nix_config.ends_with("}\n"));
        assert!(nix_config.contains("imports = ["));
        assert!(nix_config.contains("system.stateVersion"));
    }
}
